import type { Metadata } from "next";
import { Inter } from "next/font/google";

import { twm } from "@/utils/twm";

import "@/style/global.scss";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body
        className={twm(
          inter.className,
          'BODY flex-col-sbc overflow-clip min-h-screen h-screen'
        )}
      >
        <div className='LAYOUT_INNER overflow-y-scroll h-full w-[var(--layout-width)] flex-tl border-r border-l border-neutral-300 px-md pb-[25vh]'>
          {children}
        </div>
      </body>
    </html>
  )
}
